"""Canned deliverable source written by the Coder delegation path.

The registry does not call an LLM for these tasks: it classifies the task's shape
and writes a fixed, runnable module plus its test. Keeping that source here means
the generated bytes are auditable in one place instead of sitting in the middle of
the workflow's control flow, and they can be tested without driving a whole
workflow.
"""

from typing import NamedTuple, Optional

from tools.task_tags import UI_TAG, UI_KEYWORD_RE


# ``UI_KEYWORD_RE`` is defined in ``tools.task_tags`` (matched on word boundaries) and
# re-exported here so the template selector, the plan parser and Laya's domain tagger all
# read one vocabulary -- no second word list that could drift from the selector's. It
# lives in the vocabulary module rather than here so that building the parser's tag
# vocabulary does not have to import the orchestration package on the cold-start path.


class Deliverable(NamedTuple):
    """A generated module together with the test written next to it."""

    filename: str
    test_filename: str
    code: str
    test_code: str


SOLUTION_ENGINE_TEST = '''from main import SolutionEngine

def test_solution():
    engine = SolutionEngine()
    res = engine.run()
    assert res["status"] == "success"
    assert res["verified"] is True
'''

BUGFIX_REGRESSION_TEST = '''# Regression test suite for bugfix
import pytest
from main import SolutionEngine

def test_bug_regression():
    engine = SolutionEngine()
    result = engine.run()
    assert result["status"] == "success"
    assert result.get("verified") is True
'''

_UI_VIEW_HTML = '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Application View</title>
  <style>
    body { background: #07090e; color: #f1f5f9; font-family: Inter, sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
    .card { background: rgba(15, 23, 42, 0.65); border: 1px solid rgba(255, 255, 255, 0.08); backdrop-filter: blur(20px); border-radius: 16px; padding: 32px; box-shadow: 0 20px 40px rgba(0,0,0,0.5); width: 420px; text-align: center; }
    h2 { color: #38bdf8; margin-top: 0; }
    .btn { background: linear-gradient(135deg, #0284c7, #2563eb); color: #fff; border: none; padding: 10px 24px; border-radius: 8px; font-weight: 600; cursor: pointer; transition: transform 0.2s; }
    .btn:hover { transform: scale(1.03); }
  </style>
</head>
<body>
  <div class="card">
    <h2>UI Component</h2>
    <p>Rendered with glassmorphic dark theme and accessible design hierarchy.</p>
    <button class="btn" onclick="alert('Action Triggered')">Explore Module</button>
  </div>
</body>
</html>'''

_UI_VIEW_TEST = '''import os

def test_ui_view_exists():
    assert os.path.exists("my_project_workspace/ui_view.html") or os.path.exists("ui_view.html")
'''

_WEATHER_API = '''from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="Weather API Service")

class WeatherReport(BaseModel):
    city: str
    temperature_celsius: float
    condition: str

@app.get("/weather/{city}")
def get_weather(city: str):
    return {"city": city.title(), "temperature_celsius": 21.5, "condition": "Sunny"}
'''

_WEATHER_API_TEST = '''from fastapi.testclient import TestClient
from weather_api import app

client = TestClient(app)

def test_weather():
    res = client.get("/weather/Tokyo")
    assert res.status_code == 200
    assert res.json()["city"] == "Tokyo"
'''


def _solution_engine(header: str, result_key: str, result_value: str) -> str:
    """The `SolutionEngine` module, differing only in its header and echoed input."""
    return f'''{header}
from typing import Dict, Any

class SolutionEngine:
    def __init__(self, config: Dict[str, Any] = None):
        self.config = config or {{}}

    def run(self) -> Dict[str, Any]:
        return {{
            "{result_key}": "{result_value}",
            "status": "success",
            "verified": True
        }}

if __name__ == "__main__":
    engine = SolutionEngine()
    print("Execution output:", engine.run())
'''


def ui_view() -> Deliverable:
    """Glassmorphic HTML view for a UI-shaped task."""
    return Deliverable("ui_view.html", "test_ui_view.py", _UI_VIEW_HTML, _UI_VIEW_TEST)


def weather_api() -> Deliverable:
    """FastAPI weather service for a task whose title mentions weather."""
    return Deliverable("weather_api.py", "test_weather_api.py", _WEATHER_API, _WEATHER_API_TEST)


def default_engine(label: str) -> Deliverable:
    """The catch-all `main.py` module for a task with no more specific shape."""
    return Deliverable(
        "main.py", "test_main.py",
        _solution_engine(f'# Generated module for task: {label}', "task", label),
        SOLUTION_ENGINE_TEST
    )


def custom_engine(message: str) -> Deliverable:
    """The `main.py` module written in response to a free-form custom directive."""
    return Deliverable(
        "main.py", "test_main.py",
        _solution_engine(f"# Custom Solution: {message[:60]}", "prompt", message),
        SOLUTION_ENGINE_TEST
    )


def select(task_title: str, tag: Optional[str] = None) -> Deliverable:
    """Picks the template matching a task's declared shape.

    The task's domain tag decides the UI case. The title is deliberately not re-inspected
    for UI wording: the parser already turns a UI-shaped title into the tag, so a second
    inference here would be a second source of truth -- one that could pick the HTML view
    while the plan tree draws no pill, which is exactly the drift this replaced.

    Order is significant: a UI task beats the weather keyword, and anything
    unmatched falls through to the generic engine.
    """
    lowered = task_title.lower()
    if tag == UI_TAG:
        return ui_view()
    if "weather" in lowered:
        return weather_api()
    return default_engine(task_title)
